import 'package:flutter/material.dart';

class LanguageService extends ChangeNotifier {
  // Singleton pattern
  static final LanguageService _instance = LanguageService._internal();
  factory LanguageService() => _instance;
  LanguageService._internal();

  Locale _currentLocale = const Locale('ro');
  Locale get currentLocale => _currentLocale;

  void changeLanguage(String languageCode) {
    _currentLocale = Locale(languageCode);
    notifyListeners();
  }

  static final Map<String, Map<String, String>> _translations = {
    'ro': {
      'app_title': 'Parkly',
      'hello': 'Bună',
      'search_hint': 'Caută adresa sau zona...',
      'recommendations': 'Locuri în apropiere',
      'available': 'Disponibil',
      'occupied': 'Ocupat',
      'profile_title': 'Profilul meu',
      'my_cars': 'Mașinile mele',
      'settings': 'Setări',
      'payment_methods': 'Metode de plată',
      'notifications': 'Notificări',
      'support': 'Ajutor & Support',
      'language': 'Limbă',
      'security': 'Cont & Securitate',
      'logout': 'Deconectare',
      'select_language': 'Selectează limba',
      'reservations': 'Rezervări',
      'spots': 'Locuri',
      'member': 'Membru',
      'add': 'Adaugă',
      'history_title': 'Rezervările mele',
      'active': 'Active',
      'past': 'Trecute',
      'no_active_res': 'Nu ai rezervări active.',
      'no_past_res': 'Nu ai rezervări trecute.',
      'total_price': 'Preț total',
      'cancel': 'Anulează',
      'details': 'Detalii',
      'map_title': 'Harta Parcări',
      'loc_available': 'Loc Disponibil',
      'loc_occupied': 'Loc Ocupat',
      'loc_maintenance': 'În Mentenanță',
      'view_map': 'Vezi Harta',
      'my_res': 'Rezervările mele',
      'price_h': 'lei/ora',
      'see_all': 'Vezi toate',
      'loading_data': 'Căutăm cele mai bune locuri...',
      'nav_home': 'Acasa',
      'nav_history': 'Istoric',
      'nav_admin': 'Admin',
      'nav_profile': 'Profil',
      'admin_panel': 'Panou Administrare',
      'parking_spots': 'Locuri de parcare',
      'total': 'total',
      'no_spots_added': 'Nu există locuri de parcare adăugate.',
      'add_spot': 'Adauga Loc',
      'delete_spot': 'Sterge Locul',
      'delete_confirm':
          'Esti sigur ca vrei sa stergi locul selectat? Aceasta actiune este permanenta.',
      'delete': 'Sterge',
      'no_cars_yet': 'Nu ai mașini adăugate',
      'vin': 'VIN',
      'pollution_norm': 'Normă Poluare',
      'edit': 'Editează',
      'wallet_title': 'Portofel Virtual',
      'available_balance': 'Sold disponibil',
      'top_up': 'Alimentează',
      'transfer': 'Transferă',
      'transaction_history': 'Istoric Tranzacții',
      'no_transactions': 'Nicio tranzacție recentă',
      'confirm_payment': 'Confirmă Plata',
      'amount_ron': 'Sumă (RON)',
      'save': 'Salvează',
      'add_car': 'Adaugă Mașină',
      'edit_car': 'Editează Mașina',
      'full_name': 'Nume Complet',
      'model_hint': 'Model (ex: Dacia Logan)',
      'plate_hint': 'Nr. Înmatriculare',
      'coming_soon': 'Funcționalitate în lucru...',
      'actions': 'Acțiuni rapide',
      'recipient_email': 'Email destinatar',
      'transfer_details': 'Detalii transfer',
      'send': 'Trimite',
      'transfer_success': 'Transfer realizat cu succes!',
      'user_not_found': 'Utilizatorul nu a fost găsit!',
      'insufficient_funds': 'Fonduri insuficiente!',
      'cannot_transfer_self': 'Nu îți poți trimite bani singur!',
      'invalid_amount': 'Sumă invalidă!',
      'repost': 'Repostează',
      'repost_success': 'Locurile au fost repostate cu succes!',
      'unpost': 'Anulează disponibilitatea',
      'unpost_success': 'Disponibilitatea a fost anulată!',
      'expires_in': 'Expiră în',
      'expired': 'Expirat',
      'repost_error_active_res':
          'Nu poți reposta! Există o rezervare activă pe acest loc.',
      'error': 'Eroare',
      'filters': 'Filtre',
      'price_range': 'Interval preț (RON)',
      'show_available_only': 'Doar locuri disponibile',
      'apply_filters': 'Aplică filtrele',
      'reset_filters': 'Resetează',
      'maintenance': 'În mentenanță',
      'unavailable': 'Indisponibil',
      'select_hours': 'Selectează durata',
      'hours': 'ore',
      'distance_near': 'Foarte aproape de tine',
      'sort_by_distance': 'Cele mai apropiate',
      'reserve_btn': 'RESERVĂ ACUM',
      'per_hour': 'pe oră',
      'free': 'Liber',
      'occupied_label': 'Ocupat',
      'maintenance_label': 'Mentenanță',
      'account_security': 'Cont & Securitate',
      'profile_pic': 'Poza de profil',
      'upload': 'Upload',
      'personal_details': 'Date Personale',
      'name': 'Nume',
      'surname': 'Prenume',
      'username': 'Username',
      'contact_details': 'Date de Contact',
      'email': 'Email',
      'phone_number': 'Număr de telefon',
      'verified': 'Verificat',
      'not_verified': 'Neverificat',
      'save_changes': 'Salvează modificările',
      'change_password': 'Schimbare parolă',
      'current_password': 'Parola curentă',
      'new_password': 'Parola nouă',
      'confirm_new_password': 'Confirmă parola nouă',
      'update_password_btn': 'Actualizează parola',
      'deactivate_account': 'Dezactivează contul',
      'delete_account_perm': 'Șterge contul definitiv',
      'required_field': 'Câmp obligatoriu',
      'passwords_dont_match': 'Parolele nu coincid',
      'profile_updated': 'Profil actualizat cu succes!',
      'password_changed': 'Parola a fost schimbată!',
      'deactivate_title': 'Dezactivare cont',
      'deactivate_desc':
          'Această acțiune va suspenda contul tău temporar. Datele tale vor rămâne pe server, dar nu vei mai putea folosi aplicația până la reactivare.',
      'delete_title': 'Ștergere definitivă',
      'delete_desc':
          'Această acțiune este permanentă și va șterge toate datele tale. Introdu parola curentă pentru a confirma.',
      'error_password': 'Parolă incorectă sau eroare:',
      'profile_pic_updated': 'Poză de profil actualizată!',
      'upload_error': 'Eroare la încărcare:',
      'user_guide_title': 'Ghid de Utilizare',
      'guide_driver_title': 'Pentru Șoferi',
      'guide_driver_desc': 'Găsește, rezervă și plătește locul de parcare în câteva secunde direct de pe hartă.',
      'guide_driver_detail': '📍 Găsirea unui loc de parcare\n\n• Harta Interactivă: Navighează pe hartă pentru a vedea locurile disponibile în timp real.\n• Culori Pinuri:\n    ◦ Verde: Locuri libere disponibile.\n    ◦ Portocaliu: Puține locuri rămase.\n    ◦ Roșu/Gri: Loc parcare ocupat, închis sau în mentenanță.\n• Rezervare: Apasă pe pin, alege durata dorită și confirmă plata din portofel.',
      'guide_owner_title': 'Pentru Proprietari',
      'guide_owner_desc': 'Adaugă locuri noi, setează programul de disponibilitate și monitorizează încasările.',
      'guide_owner_detail': 'Dacă deții un loc de parcare, accesează secțiunea "Admin".\n\n➕ Adăugarea unui loc:\n• Apasă butonul "+" și introdu adresa, numărul locului, fotografii și prețul pe oră.\n\n🕒 Gestionarea Disponibilității:\n1. 🌙 Indisponibil temporar: Dezactivează locul manual oricând.\n2. ☀️ Program Săptămânal: Definește intervale orare specifice pentru fiecare zi.\n3. ♾️ Deschis 24/7: Locul este permanent disponibil.\n\n📊 Monitorizare:\n• Vezi în timp real cine ocupă locul tău și ce sume ai acumulat în portofel.',
      'guide_payment_title': 'Plăți & Portofel',
      'guide_payment_desc': 'Alimentează portofelul virtual pentru plăți rapide și descarcă facturile PDF instant.',
      'guide_payment_detail': '💳 Rezervarea și Plata\n\n• Portofel Virtual: Alimentează-ți contul Parkly folosind un card bancar pentru a putea rezerva locuri instant.\n• Plată Automată: La confirmarea rezervării, suma este reținută automat din soldul tău.\n• Facturare: Facturile PDF sunt generate automat pentru fiecare tranzacție și pot fi descărcate din secțiunea Istoric -> Detalii.',
      'faq_title': 'Întrebări frecvente',
      'contact_support_btn': 'Contactează Suportul',
      'legal_info': 'Informații legale',
      'terms_conditions': 'Termeni și Condiții',
      'privacy_policy': 'Politica de Confidențialitate',
      'app_version_label': 'Versiunea aplicației',
      'faq_1_q': 'Cum resetez parola?',
      'faq_1_a': 'Dacă ai uitat parola, apasă pe "Am uitat parola" în ecranul de Login. Vei primi un email pentru setarea unei parole noi.',
      'faq_2_q': 'Ce reprezintă Taxa de Serviciu?',
      'faq_2_a': 'Taxa de Serviciu (2 RON) este o sumă fixă aplicată fiecărei rezervări pentru mentenanța infrastructurii Parkly și procesarea securizată a plăților.',
      'faq_3_q': 'De ce este obligatoriu numărul de telefon?',
      'faq_3_a': 'Numărul de telefon este necesar pentru a asigura securitatea tranzacțiilor și comunicarea rapidă între utilizatori. Fără un număr valid salvat în profil, nu poți rezerva sau posta locuri de parcare.',
      'faq_4_q': 'Pot anula o rezervare?',
      'faq_4_a': 'Da, poți anula o rezervare din secțiunea Istoric. Dacă anulezi în primele 10 minute, primești refund integral în portofel (minus taxa de serviciu).',
      'faq_reported_q': 'Ce fac dacă locul rezervat este ocupat?',
      'faq_reported_a': 'Dacă ajungi la locație și locul este ocupat de o altă mașină, apasă pe butonul "Raportează loc ocupat" din detaliile rezervării. Va trebui să trimiți o poză clară, iar sistemul îți va returna banii automat după validare.',
      'faq_nav_q': 'Cum navighez către locul de parcare?',
      'faq_nav_a': 'După ce rezervi, apasă butonul "Navighează" din ecranul de detalii. Poți alege să deschizi locația exactă în Google Maps, Waze sau Apple Maps.',
      'faq_security_q': 'Sunt plățile sigure?',
      'faq_security_a': 'Absolut. Parkly folosește procesatori de plăți securizați și nu stochează datele cardului tău bancar. Tranzacțiile sunt criptate și protejate conform standardelor bancare.',
      'faq_profile_q': 'Cum îmi schimb mașina sau datele?',
      'faq_profile_a': 'Poți gestiona vehiculele din secțiunea "Mașinile mele" și datele personale (nume, email, parolă) din Profil -> Cont & Securitate.',
      'support_email_subject': '[Suport Aplicație]',
      'no_email_client_error':
          'Nu s-a găsit nicio aplicație de email instalată.',
      'faq_wallet_q': 'Cum funcționează portofelul virtual?',
      'faq_wallet_a': 'Portofelul îți permite să plătești parcările fără a introduce cardul la fiecare tranzacție. Poți transfera bani și altor utilizatori Parkly prin email.',
      'faq_transfer_q': 'Unde găsesc facturile pentru parcare?',
      'faq_transfer_a': 'Facturile fiscale se generează automat. Accesează Istoric -> selectează o rezervare trecută -> apasă "Descarcă PDF".',
      'faq_cancel_q': 'Cum contactez echipa de suport?',
      'faq_cancel_a': 'Poți deschide un chat direct cu noi apăsând butonul "Contactează Suportul" de mai jos. Suntem aici să te ajutăm!',
      'faq_cars_q': 'Trebuie să opresc manual timpul de parcare?',
      'faq_cars_a': 'Nu. Rezervările se fac pe o durată fixă selectată de tine. Timpul expiră automat și locul devine disponibil pentru alți șoferi.',
      'faq_extend_q': 'Cât câștig ca proprietar?',
      'faq_extend_a': 'Proprietarii primesc 80% din tariful de bază setat pe oră. Banii sunt transferați în portofelul virtual imediat după finalizarea rezervării.',
      'notif_settings_title': 'Setări Notificări',
      'notif_reservations': 'Rezervări și Confirmări',
      'notif_reservations_desc':
          'Primește actualizări despre statusul rezervărilor tale.',
      'notif_expiry': 'Avertizări expirare timp',
      'notif_expiry_desc': 'Alerte cu 15 minute înainte de expirarea parcării.',
      'notif_promos': 'Promoții și Noutăți',
      'notif_promos_desc':
          'Află primul despre oferte speciale și funcționalități noi.',
      'notif_system_settings': 'Setări notificări dispozitiv',
      'invoices_title': 'Facturile mele',
      'nav_messages': 'Mesaje',
      'swipe_more_photos': 'Glisați pentru mai multe poze',
      'spot_number_label': 'Număr Loc',
      'start_time': 'Ora începerii',
      'select_car': 'Selectează Mașina',
      'no_cars_added_error': 'Nu ai nicio mașină adăugată în profil!',
      'choose_plate': 'Alege numărul de înmatriculare',
      'owner': 'Proprietar',
      'about_location': 'Despre locație',
      'availability_schedule': 'Program Disponibilitate',
      'facilities': 'Facilități',
      'no_facilities': 'Nu sunt facilități specificate.',
      'free_spots': 'locuri libere',
      'total_spots': 'Total',
      'maintenance_notice':
          'Acest loc este în mentenanță pentru siguranța dumneavoastră sau lucrări de infrastructură.',
      'total_payment': 'Total Plată',
      'choose_car_btn': 'ALEGE MAȘINA',
      'reservation_confirmed': 'Rezervare Confirmată!',
      'res_success_desc':
          'Locul tău a fost rezervat cu succes. Poți vedea detaliile în istoricul tău.',
      'close': 'ÎNCHIDE',
      'res_details_title': 'Detalii Rezervare',
      'res_active': 'Rezervare Activă',
      'res_completed': 'Rezervare Finalizată',
      'location_info': 'Locație Parcare',
      'coordinates': 'Coordonate',
      'navigate': 'Navighează',
      'time_interval': 'Interval Orar',
      'from': 'De la',
      'until': 'Până la',
      'invoice_details': 'Detalii Factură & Plată',
      'invoice_number': 'Nr. Factură',
      'issue_date': 'Data Emiterii',
      'gross_price': 'Preț Brut',
      'net_price': 'Preț Net',
      'payment_confirmed_wallet': 'Plată confirmată prin Portofel',
      'swipe_for_photo': 'Glisați pentru foto',
      'payment_details': 'Detalii Plată',
      'total_paid': 'Total Plătit',
      'res_id_label': 'ID Rezervare',
      'vat_label': 'TVA (20%)',
      'monday': 'Luni',
      'tuesday': 'Marți',
      'wednesday': 'Miercuri',
      'thursday': 'Joi',
      'friday': 'Vineri',
      'saturday': 'Sâmbătă',
      'sunday': 'Duminică',
      'facility_videocam': 'Supraveghere 24/7',
      'facility_lighting': 'Iluminat nocturn',
      'facility_charging': 'Stație încărcare',
      'facility_private': 'Zonă privată',
      'facility_barrier': 'Acces barieră',
      'facility_covered': 'Acoperit',
      'facility_default': 'Dotare parcare',
      'facility_paza': 'Pază umană',
      'facility_asphalt': 'Asfaltat',
      'facility_markings': 'Marcat',
      'facility_cleaning': 'Curățenie',
      'facility_transit': 'Lângă transport public',
      'facility_disabled': 'Acces Dizabilități',
      'price_weekend': 'Weekend',
      'price_night': 'Noapte',
      'price_peak': 'Vârf',
      'price_surge': 'Tarif',
      'price_discount': 'Reducere',
      'price_long_stay': 'Reducere de Durată (-10%)',
      'past_time_error': 'Nu poți face o rezervare în trecut!',
      'no_spots_error': 'Nu mai sunt locuri libere!',
      'closed': 'Închis',
      'sort_by': 'Sortează după',
      'price': 'Preț',
      'no_results_filters': 'Niciun rezultat pentru filtrele tale',
      'driver_welcome': 'Șoferule',
      'cancel_confirmation':
          'Ești sigur că vrei să anulezi această rezervare? Această acțiune nu poate fi anulată.',
      'no': 'Nu',
      'yes_cancel': 'Da, Anulează',
      'no_messages': 'Niciun mesaj nou',
      'messages_updated': 'Mesaje actualizate',
      'messages_title': 'Mesaje & Notificări',
      'tenant_details': 'Detalii chiriaș',
      'name_label': 'Nume:',
      'email_label': 'Email:',
      'car_label': 'Mașină:',
      'interval_label': 'Interval:',
      'always_available': 'Deschis 24/7',
      'manually_disabled': 'Indisponibil temporar',
      'delete_all_notif_title': 'Șterge toate notificările',
      'delete_all_notif_confirm': 'Ești sigur că vrei să ștergi toate notificările? Această acțiune este permanentă.',
      'location_details': 'Detalii Locație',
      'parking_name': 'Nume Parcare',
      'address_auto': 'Adresă (Auto-completată)',
      'detailed_description': 'Descriere Detaliată',
      'spot_number_on_pavement': 'Număr Loc Parcare (de pe asfalt)',
      'weekly_availability_schedule': 'Program Disponibilitate Săptămânal',
      'street_view_preview': 'Previzualizare Street View',
      'parking_photo': 'Fotografie Loc Parcare',
      'confirm_and_save': 'CONFIRMĂ ȘI SALVEAZĂ',
      'required_field_error': 'Câmp obligatoriu',
      'parking_created_success': 'Loc de parcare creat cu succes!',
      'parking_updated_success': 'Loc de parcare actualizat cu succes!',
      'save_error': 'Eroare la salvare:',
      'notif_res_confirmed': 'Rezervare Confirmată',
      'notif_money_received': 'Bani primiți în portofel',
      'notif_spot_rented': 'Loc închiriat',
      'notif_expiry_warning': 'Atenție: Expiră parcarea!',
      'notif_expiry_urgent': 'Urgent: Parcare aproape de final!',
      'trans_bonus_admin': 'Bonus Admin',
      'trans_rental_income': 'Încasare chirie',
      'trans_refund': 'Refundare rezervare',
      'trans_cancel_refund': 'Anulare rezervare (+Refund)',
      'trans_transfer_sent': 'Transfer trimis către',
      'trans_transfer_received': 'Transfer primit de la',
      'trans_payment': 'Plată parcare',
      'trans_initial_credit': 'Bonus de bun venit',
      'trans_top_up': 'Alimentare portofel',
      'trans_refund_reversal': 'Refundare (stornare)',
      'notif_res_confirmed_title': 'Rezervare Confirmată',
      'notif_res_confirmed_msg': 'Ai rezervat locul',
      'notif_res_cancelled_title': 'Rezervare Anulată',
      'notif_res_cancelled_msg': 'Rezervarea ta a fost anulată cu succes.',
      'notif_refund_processed_title': 'Refund Realizat',
      'notif_refund_processed_msg': 'Suma a fost returnată în portofelul tău.',
      'notif_money_received_title': 'Bani primiți în portofel',
      'notif_money_received_msg': 'Ai primit bani pentru închiriere.',
      'notif_spot_rented_title': 'Loc închiriat',
      'notif_spot_rented_msg': 'Cineva a închiriat locul tău.',
      'notif_report_received_title': '🚩 Raport Trimis',
      'notif_report_received_msg': 'Am primit raportul tău pentru locul ocupat. Un operator îl va analiza în cel mult 15 minute.',
      'notif_report_decision_title': '⚖️ Decizie Suport',
      'notif_report_decision_refund': 'Raport aprobat! Suma a fost returnată în portofelul tău.',
      'notif_report_decision_rejected': 'Raport respins. Dovada foto nu a fost concludentă sau ești prea departe.',
      'status_closed_schedule': 'ÎNCHIS (ORAR)',
      'status_deactivated': 'DEZACTIVAT',
      'status_247_free': '24/7 - LIBERE',
      'invoice_status_emis': 'EMIS',
      'invoice_status_stornat': 'STORNAT',
      'download_pdf': 'DESCARCĂ PDF',
      'status_reported': 'RAPORTAT',
      'status_cancelled': 'ANULAT',
      'choose_nav_app': 'Alege aplicația de navigare',
      'owner_profile': 'Profil Proprietar',
      'chat_with_owner': 'Trimite mesaj',
      'owner_spots': 'Locuri de parcare postate',
      'no_available_spots_owner': 'Acest utilizator nu are alte locuri disponibile momentan.',
      'hour_short': 'h',
      'official_parkly_spots': 'Locuri oficiale gestionate de Parkly',
      'checkout_summary': 'Rezumat Plată',
      'parking_price': 'Preț Parcare',
      'service_fee': 'Taxă Serviciu Sistem',
      'surge_adjustment': 'Ajustare Tarif (Vârf)',
      'discount_adjustment': 'Ajustare Tarif (Reducere)',
      'confirm_and_pay': 'CONFIRMĂ ȘI PLĂTEȘTE',
      'report_occupied': 'Loc ocupat de altcineva',
      'report_occupied_confirm': 'Ești sigur că vrei să raportezi locul ca fiind ocupat? Rezervarea va fi anulată și vei primi banii înapoi integral.',
      'report_success': 'Raport trimis. Refund realizat cu succes!',
      'extend_reservation': 'Prelungește',
      'extend_success': 'Rezervare prelungită cu succes!',
      'rate_experience': 'Cum a fost experiența ta?',
      'submit_rating': 'Trimite recenzia',
      'rating_success': 'Îți mulțumim pentru feedback!',
      'spot_suspended_notice': 'Acest loc a fost suspendat temporar pentru verificări.',
      'cancel_report_title': 'Anulare și Raportare',
      'cancel_report_warning': 'Rezervarea va fi ANULATĂ imediat.',
      'cancel_report_refund_info': '• Vei primi banii înapoi (fără Garanția de 2 RON).',
      'cancel_report_guarantee_info': '• Dacă suportul aprobă raportul, vei primi și Garanția înapoi.',
      'confirm_btn': 'CONFIRMĂ',
      'report_sent_success': 'Raport trimis către suport.',
      'add_comment_optional': 'Adaugă un comentariu (opțional)...',
      'cancel_report_btn': 'ANULARE ȘI RAPORT',
      'res_cancelled_voided': 'Rezervare Anulată (STORNAT)',
      'spot_occupied_pending': '🚩 Loc Ocupat (În analiză)',
      'report_accepted_refunded': '✅ Raport Acceptat (Garanție Refundată)',
      'report_refused': '❌ Raport Refuzat',
      'download_invoice_pdf': 'DESCARCĂ FACTURA (PDF)',
    },
    'en': {
      'app_title': 'Parkly',
      'hello': 'Hello',
      'search_hint': 'Search address or area...',
      'recommendations': 'Nearby spots',
      'available': 'Available',
      'occupied': 'Occupied',
      'profile_title': 'My Profile',
      'my_cars': 'My Cars',
      'settings': 'Settings',
      'payment_methods': 'Payment Methods',
      'notifications': 'Notifications',
      'support': 'Help & Support',
      'language': 'Language',
      'security': 'Account & Security',
      'logout': 'Logout',
      'select_language': 'Select language',
      'reservations': 'Reservations',
      'spots': 'Spots',
      'member': 'Member',
      'add': 'Add',
      'history_title': 'My Reservations',
      'active': 'Active',
      'past': 'Past',
      'no_active_res': 'No active reservations.',
      'no_past_res': 'No past reservations.',
      'total_price': 'Total price',
      'cancel': 'Cancel',
      'details': 'Details',
      'map_title': 'Parking Map',
      'loc_available': 'Spot Available',
      'loc_occupied': 'Spot Occupied',
      'loc_maintenance': 'Under Maintenance',
      'view_map': 'View Map',
      'my_res': 'My reservations',
      'price_h': 'lei/hour',
      'see_all': 'See all',
      'loading_data': 'Looking for the best spots...',
      'nav_home': 'Home',
      'nav_history': 'History',
      'nav_admin': 'Admin',
      'nav_profile': 'Profile',
      'admin_panel': 'Admin Panel',
      'parking_spots': 'Parking Spots',
      'total': 'total',
      'no_spots_added': 'No parking spots added yet.',
      'add_spot': 'Add Spot',
      'delete_spot': 'Delete Spot',
      'delete_confirm':
          'Are you sure you want to delete this spot? This action is permanent.',
      'delete': 'Delete',
      'no_cars_yet': 'No cars added yet',
      'vin': 'VIN',
      'pollution_norm': 'Pollution Norm',
      'edit': 'Edit',
      'wallet_title': 'Virtual Wallet',
      'available_balance': 'Available balance',
      'top_up': 'Top Up',
      'transfer': 'Transfer',
      'transaction_history': 'Transaction History',
      'no_transactions': 'No recent transactions',
      'confirm_payment': 'Confirm Payment',
      'amount_ron': 'Amount (RON)',
      'save': 'Save',
      'add_car': 'Add Car',
      'edit_car': 'Edit Car',
      'full_name': 'Full Name',
      'model_hint': 'Model (e.g. Dacia Logan)',
      'plate_hint': 'License Plate',
      'coming_soon': 'Feature coming soon...',
      'actions': 'Quick Actions',
      'recipient_email': 'Recipient Email',
      'transfer_details': 'Transfer Details',
      'send': 'Send',
      'transfer_success': 'Transfer successful!',
      'user_not_found': 'User not found!',
      'insufficient_funds': 'Insufficient funds!',
      'cannot_transfer_self': 'You cannot transfer money to yourself!',
      'invalid_amount': 'Invalid amount!',
      'repost': 'Repost',
      'repost_success': 'Spots reposted successfully!',
      'unpost': 'Unpost',
      'unpost_success': 'Availability cancelled successfully!',
      'expires_in': 'Expires in',
      'expired': 'Expired',
      'repost_error_active_res':
          'Cannot repost! There is an active reservation for this spot.',
      'error': 'Error',
      'filters': 'Filters',
      'price_range': 'Price Range (RON)',
      'show_available_only': 'Only available spots',
      'apply_filters': 'Apply filters',
      'reset_filters': 'Reset',
      'maintenance': 'Under Maintenance',
      'unavailable': 'Unavailable',
      'select_hours': 'Select duration',
      'hours': 'hours',
      'distance_near': 'Very close to you',
      'sort_by_distance': 'Closest to you',
      'reserve_btn': 'RESERVE NOW',
      'per_hour': 'per hour',
      'free': 'Free',
      'occupied_label': 'Occupied',
      'maintenance_label': 'Maintenance',
      'account_security': 'Account & Security',
      'profile_pic': 'Profile Picture',
      'upload': 'Upload',
      'personal_details': 'Personal Details',
      'name': 'Name',
      'surname': 'Surname',
      'username': 'Username',
      'contact_details': 'Contact Details',
      'email': 'Email',
      'phone_number': 'Phone number',
      'verified': 'Verified',
      'not_verified': 'Not verified',
      'save_changes': 'Save changes',
      'change_password': 'Change password',
      'current_password': 'Current password',
      'new_password': 'New password',
      'confirm_new_password': 'Confirm new password',
      'update_password_btn': 'Update password',
      'deactivate_account': 'Deactivate account',
      'delete_account_perm': 'Delete account permanently',
      'required_field': 'Required field',
      'passwords_dont_match': 'Passwords do not match',
      'profile_updated': 'Profile updated successfully!',
      'password_changed': 'Password updated!',
      'deactivate_title': 'Deactivate account',
      'deactivate_desc':
          'This action will temporarily suspend your account. Your data will remain on the server, but you will not be able to use the app until reactivation.',
      'delete_title': 'Permanent deletion',
      'delete_desc':
          'This action is permanent and will delete all your data. Enter your current password to confirm.',
      'error_password': 'Incorrect password or error:',
      'profile_pic_updated': 'Profile picture updated!',
      'upload_error': 'Upload error:',
      'user_guide_title': 'User Guide',
      'guide_driver_title': 'For Drivers',
      'guide_driver_desc': 'Find, book and pay for your parking spot in seconds directly from the map.',
      'guide_driver_detail': '📍 Finding a spot\n\n• Interactive Map: Navigate the map to see available spots in real-time.\n• Pin Colors:\n    ◦ Green: Available spots.\n    ◦ Orange: Few spots left.\n    ◦ Red/Gray: Occupied, closed, or under maintenance.\n• Booking: Tap a pin, choose your desired duration, and confirm payment from your wallet.',
      'guide_owner_title': 'For Owners',
      'guide_owner_desc': 'Add new spots, set the availability schedule and monitor your earnings.',
      'guide_owner_detail': 'If you own a parking spot, access the "Admin" section.\n\n➕ Adding a spot:\n• Tap the "+" button and enter the address, spot number, photos, and hourly price.\n\n🕒 Availability Management:\n1. 🌙 Temporarily Unavailable: Manually disable the spot anytime.\n2. ☀️ Weekly Schedule: Define specific time intervals for each day.\n3. ♾️ Always Available 24/7: The spot is permanently open.\n\n📊 Monitoring:\n• See in real-time who occupies your spot and the earnings accumulated in your wallet.',
      'guide_payment_title': 'Payments & Wallet',
      'guide_payment_desc': 'Top up your virtual wallet for quick payments and download PDF invoices instantly.',
      'guide_payment_detail': '💳 Booking & Payment\n\n• Virtual Wallet: Top up your Parkly account using a credit card to book spots instantly.\n• Automatic Payment: Upon booking confirmation, the amount is automatically deducted from your balance.\n• Invoicing: PDF invoices are automatically generated for each transaction and can be downloaded from History -> Details.',
      'faq_title': 'Frequently Asked Questions',
      'contact_support_btn': 'Contact Support',
      'legal_info': 'Legal Information',
      'terms_conditions': 'Terms & Conditions',
      'privacy_policy': 'Privacy Policy',
      'app_version_label': 'App Version',
      'faq_1_q': 'How do I reset my password?',
      'faq_1_a': 'If you forgot your password, tap "Forgot Password" on the Login screen. You will receive an email to set a new one.',
      'faq_2_q': 'What is the Service Fee?',
      'faq_2_a': 'The Service Fee (2 RON) is a fixed amount applied to each booking for Parkly infrastructure maintenance and secure payment processing.',
      'faq_3_q': 'Why is a phone number mandatory?',
      'faq_3_a': 'A phone number is required to ensure transaction security and rapid communication between users. Without a valid number in your profile, you cannot book or post parking spots.',
      'faq_4_q': 'Can I cancel a reservation?',
      'faq_4_a': 'Yes, you can cancel a reservation from the History section. If you cancel within the first 10 minutes, you receive a full refund in your wallet (minus the service fee).',
      'faq_reported_q': 'What if the reserved spot is occupied?',
      'faq_reported_a': 'If you arrive and the spot is occupied by another car, use the "Report occupied spot" button in the reservation details. You will need to send a clear photo, and the system will automatically refund you after validation.',
      'faq_nav_q': 'How do I navigate to the spot?',
      'faq_nav_a': 'After booking, tap the "Navigate" button in the details screen. You can choose to open the exact location in Google Maps, Waze, or Apple Maps.',
      'faq_security_q': 'Are payments secure?',
      'faq_security_a': 'Absolutely. Parkly uses secure payment processors and does not store your bank card data. Transactions are encrypted and protected according to banking standards.',
      'faq_profile_q': 'How do I change my car or info?',
      'faq_profile_a': 'You can manage your vehicles in "My Cars" and update personal info (name, email, password) in Profile -> Account & Security.',
      'support_email_subject': '[App Support]',
      'no_email_client_error': 'No email app found installed.',
      'faq_wallet_q': 'How does the virtual wallet work?',
      'faq_wallet_a': 'The wallet allows you to pay for parking without entering your card for every transaction. You can also transfer money to other Parkly users via email.',
      'faq_transfer_q': 'Where can I find my parking invoices?',
      'faq_transfer_a': 'Tax invoices are automatically generated. Go to History -> select a past reservation -> tap "Download PDF".',
      'faq_cancel_q': 'How do I contact the support team?',
      'faq_cancel_a': 'You can open a direct chat with us by tapping the "Contact Support" button below. We are here to help!',
      'faq_cars_q': 'Do I need to manually stop the parking time?',
      'faq_cars_a': 'No. Bookings are made for a fixed duration selected by you. The time expires automatically and the spot becomes available for other drivers.',
      'faq_extend_q': 'How much do I earn as an owner?',
      'faq_extend_a': 'Owners receive 80% of the set hourly base rate. The funds are transferred to your virtual wallet immediately after the booking is completed.',
      'notif_settings_title': 'Notification Settings',
      'notif_reservations': 'Reservations & Confirmations',
      'notif_reservations_desc': 'Receive updates about your booking status.',
      'notif_expiry': 'Time Expiry Alerts',
      'notif_expiry_desc': 'Alerts 15 minutes before parking expires.',
      'notif_promos': 'Promotions & News',
      'notif_promos_desc':
          'Be the first to know about special offers and new features.',
      'notif_system_settings': 'Device Notification Settings',
      'invoices_title': 'My Invoices',
      'nav_messages': 'Messages',
      'swipe_more_photos': 'Swipe for more photos',
      'spot_number_label': 'Spot Number',
      'start_time': 'Start Time',
      'select_car': 'Select Car',
      'no_cars_added_error': 'You have no cars added to your profile!',
      'choose_plate': 'Choose license plate',
      'owner': 'Owner',
      'about_location': 'About location',
      'availability_schedule': 'Availability Schedule',
      'facilities': 'Facilities',
      'no_facilities': 'No facilities specified.',
      'free_spots': 'free spots',
      'total_spots': 'Total',
      'maintenance_notice':
          'This spot is under maintenance for your safety or infrastructure works.',
      'total_payment': 'Total Payment',
      'choose_car_btn': 'CHOOSE CAR',
      'reservation_confirmed': 'Reservation Confirmed!',
      'res_success_desc':
          'Your spot was successfully reserved. You can see the details in your history.',
      'close': 'CLOSE',
      'res_details_title': 'Reservation Details',
      'res_active': 'Active Reservation',
      'res_completed': 'Completed Reservation',
      'location_info': 'Parking Location',
      'coordinates': 'Coordinates',
      'navigate': 'Navigate',
      'time_interval': 'Time Interval',
      'from': 'From',
      'until': 'Until',
      'invoice_details': 'Invoice & Payment Details',
      'invoice_number': 'Invoice No.',
      'issue_date': 'Issue Date',
      'gross_price': 'Gross Price',
      'net_price': 'Net Price',
      'payment_confirmed_wallet': 'Payment confirmed via Wallet',
      'swipe_for_photo': 'Swipe for photo',
      'payment_details': 'Payment Details',
      'total_paid': 'Total Paid',
      'res_id_label': 'Reservation ID',
      'vat_label': 'VAT (20%)',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',
      'facility_videocam': '24/7 Surveillance',
      'facility_lighting': 'Night lighting',
      'facility_charging': 'Charging station',
      'facility_private': 'Private area',
      'facility_barrier': 'Barrier access',
      'facility_covered': 'Covered',
      'facility_default': 'Parking feature',
      'facility_paza': 'Human security',
      'facility_asphalt': 'Asphalt',
      'facility_markings': 'Marked',
      'facility_cleaning': 'Cleaning',
      'facility_transit': 'Near public transit',
      'facility_disabled': 'Disabled Access',
      'price_weekend': 'Weekend',
      'price_night': 'Night',
      'price_peak': 'Peak',
      'price_surge': 'Surge',
      'price_discount': 'Discount',
      'price_long_stay': 'Long Stay Discount (-10%)',
      'past_time_error': 'You cannot make a reservation in the past!',
      'no_spots_error': 'No more free spots available!',
      'closed': 'Closed',
      'sort_by': 'Sort by',
      'price': 'Price',
      'no_results_filters': 'No results for your filters',
      'driver_welcome': 'Driver',
      'cancel_confirmation':
          'Are you sure you want to cancel this reservation? This action cannot be undone.',
      'no': 'No',
      'yes_cancel': 'Yes, Cancel',
      'no_messages': 'No new messages',
      'messages_updated': 'Messages updated',
      'messages_title': 'Messages & Notifications',
      'tenant_details': 'Tenant Details',
      'name_label': 'Name:',
      'email_label': 'Email:',
      'car_label': 'Car:',
      'interval_label': 'Interval:',
      'always_available': 'Always Available 24/7',
      'manually_disabled': 'Temporarily Unavailable',
      'delete_all_notif_title': 'Delete all notifications',
      'delete_all_notif_confirm': 'Are you sure you want to delete all notifications? This action is permanent.',
      'location_details': 'Location Details',
      'parking_name': 'Parking Name',
      'address_auto': 'Address (Auto-completed)',
      'detailed_description': 'Detailed Description',
      'spot_number_on_pavement': 'Parking Spot Number (on pavement)',
      'weekly_availability_schedule': 'Weekly Availability Schedule',
      'street_view_preview': 'Street View Preview',
      'parking_photo': 'Parking Spot Photo',
      'confirm_and_save': 'CONFIRM AND SAVE',
      'required_field_error': 'Required field',
      'parking_created_success': 'Parking spot created successfully!',
      'parking_updated_success': 'Parking spot updated successfully!',
      'save_error': 'Save error:',
      'notif_res_confirmed': 'Reservation Confirmed',
      'notif_money_received': 'Money received in wallet',
      'notif_spot_rented': 'Spot rented',
      'notif_expiry_warning': 'Attention: Parking expires!',
      'notif_expiry_urgent': 'Urgent: Parking almost over!',
      'trans_bonus_admin': 'Admin Bonus',
      'trans_rental_income': 'Rental income',
      'trans_refund': 'Reservation refund',
      'trans_cancel_refund': 'Reservation cancellation (+Refund)',
      'trans_transfer_sent': 'Transfer sent to',
      'trans_transfer_received': 'Transfer received from',
      'trans_payment': 'Parking payment',
      'trans_initial_credit': 'Welcome bonus',
      'trans_top_up': 'Wallet top-up',
      'trans_refund_reversal': 'Refund (reversal)',
      'notif_res_confirmed_title': 'Reservation Confirmed',
      'notif_res_confirmed_msg': 'You reserved the spot',
      'notif_res_cancelled_title': 'Reservation Cancelled',
      'notif_res_cancelled_msg': 'Your reservation was successfully cancelled.',
      'notif_refund_processed_title': 'Refund Processed',
      'notif_refund_processed_msg': 'The amount was returned to your wallet.',
      'notif_money_received_title': 'Money received in wallet',
      'notif_money_received_msg': 'You received money for renting.',
      'notif_spot_rented_title': 'Spot rented',
      'notif_spot_rented_msg': 'Someone rented your spot.',
      'notif_report_received_title': '🚩 Report Submitted',
      'notif_report_received_msg': 'We received your report. A support agent will review it within 15 minutes.',
      'notif_report_decision_title': '⚖️ Support Decision',
      'notif_report_decision_refund': 'Report approved! The amount has been refunded to your wallet.',
      'notif_report_decision_rejected': 'Report rejected. The photo evidence was not conclusive or you are too far.',
      'status_closed_schedule': 'CLOSED (SCHEDULE)',
      'status_deactivated': 'DEACTIVATED',
      'status_247_free': '24/7 - FREE',
      'invoice_status_emis': 'ISSUED',
      'invoice_status_stornat': 'VOIDED',
      'download_pdf': 'DOWNLOAD PDF',
      'status_cancelled': 'CANCELLED',
      'choose_nav_app': 'Choose navigation app',
      'owner_profile': 'Owner Profile',
      'chat_with_owner': 'Send message',
      'owner_spots': 'Posted parking spots',
      'no_available_spots_owner': 'This user has no other available spots at the moment.',
      'hour_short': 'h',
      'official_parkly_spots': 'Official spots managed by Parkly',
      'checkout_summary': 'Checkout Summary',
      'parking_price': 'Parking Price',
      'service_fee': 'System Service Fee',
      'surge_adjustment': 'Rate Adjustment (Surge)',
      'discount_adjustment': 'Rate Adjustment (Discount)',
      'confirm_and_pay': 'CONFIRM AND PAY',
      'report_occupied': 'Spot occupied by someone else',
      'report_occupied_confirm': 'Are you sure you want to report the spot as occupied? The reservation will be cancelled and you will receive a full refund.',
      'report_success': 'Report sent. Refund processed successfully!',
      'extend_reservation': 'Extend',
      'extend_success': 'Reservation extended successfully!',
      'rate_experience': 'How was your experience?',
      'submit_rating': 'Submit review',
      'rating_success': 'Thank you for your feedback!',
      'spot_suspended_notice': 'This spot has been temporarily suspended for checks.',
      'cancel_report_title': 'Cancel and Report',
      'cancel_report_warning': 'The reservation will be CANCELLED immediately.',
      'cancel_report_refund_info': '• You will receive your money back (excluding the 2 RON Guarantee).',
      'cancel_report_guarantee_info': '• If support approves the report, you will also receive the Guarantee back.',
      'confirm_btn': 'CONFIRM',
      'report_sent_success': 'Report sent to support.',
      'add_comment_optional': 'Add a comment (optional)...',
      'cancel_report_btn': 'CANCEL AND REPORT',
      'res_cancelled_voided': 'Reservation Cancelled (VOIDED)',
      'spot_occupied_pending': '🚩 Spot Occupied (Pending)',
      'report_accepted_refunded': '✅ Report Accepted (Guarantee Refunded)',
      'report_refused': '❌ Report Refused',
      'download_invoice_pdf': 'DOWNLOAD INVOICE (PDF)',
    }
  };

  String translate(String key) {
    return _translations[_currentLocale.languageCode]?[key] ?? key;
  }
}
