[env:uno]
platform = atmelavr
board = uno
framework = arduino

; Adauga liniile de mai jos pentru a instala bibliotecile:
lib_deps = 
	adafruit/Adafruit GFX Library
	adafruit/Adafruit SSD1306
	adafruit/DHT sensor library
	adafruit/Adafruit Unified Sensor