// Mocks generated by Mockito 5.4.6 from annotations
// in parkly/test/services/auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloud_firestore/cloud_firestore.dart' as _i7;
import 'package:google_sign_in/google_sign_in.dart' as _i2;
import 'package:google_sign_in_platform_interface/google_sign_in_platform_interface.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:parkly/services/database_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGoogleSignInAuthentication_0 extends _i1.SmartFake
    implements _i2.GoogleSignInAuthentication {
  _FakeGoogleSignInAuthentication_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GoogleSignIn].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignIn extends _i1.Mock implements _i2.GoogleSignIn {
  MockGoogleSignIn() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SignInOption get signInOption => (super.noSuchMethod(
        Invocation.getter(#signInOption),
        returnValue: _i3.SignInOption.standard,
      ) as _i3.SignInOption);

  @override
  List<String> get scopes => (super.noSuchMethod(
        Invocation.getter(#scopes),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get forceCodeForRefreshToken => (super.noSuchMethod(
        Invocation.getter(#forceCodeForRefreshToken),
        returnValue: false,
      ) as bool);

  @override
  _i4.Stream<_i2.GoogleSignInAccount?> get onCurrentUserChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onCurrentUserChanged),
        returnValue: _i4.Stream<_i2.GoogleSignInAccount?>.empty(),
      ) as _i4.Stream<_i2.GoogleSignInAccount?>);

  @override
  _i4.Future<_i2.GoogleSignInAccount?> signInSilently({
    bool? suppressErrors = true,
    bool? reAuthenticate = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInSilently,
          [],
          {
            #suppressErrors: suppressErrors,
            #reAuthenticate: reAuthenticate,
          },
        ),
        returnValue: _i4.Future<_i2.GoogleSignInAccount?>.value(),
      ) as _i4.Future<_i2.GoogleSignInAccount?>);

  @override
  _i4.Future<bool> isSignedIn() => (super.noSuchMethod(
        Invocation.method(
          #isSignedIn,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.GoogleSignInAccount?> signIn() => (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
        ),
        returnValue: _i4.Future<_i2.GoogleSignInAccount?>.value(),
      ) as _i4.Future<_i2.GoogleSignInAccount?>);

  @override
  _i4.Future<_i2.GoogleSignInAccount?> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<_i2.GoogleSignInAccount?>.value(),
      ) as _i4.Future<_i2.GoogleSignInAccount?>);

  @override
  _i4.Future<_i2.GoogleSignInAccount?> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i4.Future<_i2.GoogleSignInAccount?>.value(),
      ) as _i4.Future<_i2.GoogleSignInAccount?>);

  @override
  _i4.Future<bool> requestScopes(List<String>? scopes) => (super.noSuchMethod(
        Invocation.method(
          #requestScopes,
          [scopes],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> canAccessScopes(
    List<String>? scopes, {
    String? accessToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #canAccessScopes,
          [scopes],
          {#accessToken: accessToken},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [GoogleSignInAccount].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignInAccount extends _i1.Mock
    implements _i2.GoogleSignInAccount {
  MockGoogleSignInAccount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get email => (super.noSuchMethod(
        Invocation.getter(#email),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#email),
        ),
      ) as String);

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  _i4.Future<_i2.GoogleSignInAuthentication> get authentication =>
      (super.noSuchMethod(
        Invocation.getter(#authentication),
        returnValue: _i4.Future<_i2.GoogleSignInAuthentication>.value(
            _FakeGoogleSignInAuthentication_0(
          this,
          Invocation.getter(#authentication),
        )),
      ) as _i4.Future<_i2.GoogleSignInAuthentication>);

  @override
  _i4.Future<Map<String, String>> get authHeaders => (super.noSuchMethod(
        Invocation.getter(#authHeaders),
        returnValue: _i4.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i4.Future<Map<String, String>>);

  @override
  _i4.Future<void> clearAuthCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAuthCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [GoogleSignInAuthentication].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignInAuthentication extends _i1.Mock
    implements _i2.GoogleSignInAuthentication {
  MockGoogleSignInAuthentication() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i6.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveUserData({
    required String? uid,
    required String? email,
    String? displayName,
    String? photoURL,
    String? role = 'user',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserData,
          [],
          {
            #uid: uid,
            #email: email,
            #displayName: displayName,
            #photoURL: photoURL,
            #role: role,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<_i7.DocumentSnapshot<Object?>> getUserData(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserData,
          [uid],
        ),
        returnValue: _i4.Stream<_i7.DocumentSnapshot<Object?>>.empty(),
      ) as _i4.Stream<_i7.DocumentSnapshot<Object?>>);

  @override
  _i4.Future<void> updateDisplayName(String? uid, String? newName) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDisplayName,
          [uid, newName],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addUserCar(String? uid, String? model, String? plate,
          String? vin, String? emission) =>
      (super.noSuchMethod(
        Invocation.method(
          #addUserCar,
          [uid, model, plate, vin, emission],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<_i7.QuerySnapshot<Object?>> getUserCars(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserCars,
          [uid],
        ),
        returnValue: _i4.Stream<_i7.QuerySnapshot<Object?>>.empty(),
      ) as _i4.Stream<_i7.QuerySnapshot<Object?>>);

  @override
  _i4.Future<void> updateUserCar(String? uid, String? carId, String? model,
          String? plate, String? vin, String? emission) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserCar,
          [uid, carId, model, plate, vin, emission],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateFCMToken(String? uid, String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFCMToken,
          [uid, token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUserCar(String? uid, String? carId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserCar,
          [uid, carId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addParkingSpot({
    required String? ownerId,
    required String? title,
    required String? description,
    required String? address,
    required double? pricePerHour,
    required _i7.GeoPoint? location,
    List<String>? images = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addParkingSpot,
          [],
          {
            #ownerId: ownerId,
            #title: title,
            #description: description,
            #address: address,
            #pricePerHour: pricePerHour,
            #location: location,
            #images: images,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<_i7.QuerySnapshot<Object?>> getAvailableSpots() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableSpots,
          [],
        ),
        returnValue: _i4.Stream<_i7.QuerySnapshot<Object?>>.empty(),
      ) as _i4.Stream<_i7.QuerySnapshot<Object?>>);

  @override
  _i4.Future<void> createReservation({
    required String? userId,
    required String? spotId,
    required String? parkingName,
    required DateTime? startTime,
    required DateTime? endTime,
    required double? totalPrice,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createReservation,
          [],
          {
            #userId: userId,
            #spotId: spotId,
            #parkingName: parkingName,
            #startTime: startTime,
            #endTime: endTime,
            #totalPrice: totalPrice,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<_i7.QuerySnapshot<Object?>> getUserReservations(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserReservations,
          [userId],
        ),
        returnValue: _i4.Stream<_i7.QuerySnapshot<Object?>>.empty(),
      ) as _i4.Stream<_i7.QuerySnapshot<Object?>>);

  @override
  _i4.Future<void> updateReservationStatus(String? resId, String? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReservationStatus,
          [resId, status],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addWalletCredits(String? uid, double? amount) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWalletCredits,
          [uid, amount],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> transferMoneyByEmail({
    required String? senderUid,
    required String? recipientEmail,
    required double? amount,
    required String? details,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transferMoneyByEmail,
          [],
          {
            #senderUid: senderUid,
            #recipientEmail: recipientEmail,
            #amount: amount,
            #details: details,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> toggleFavorite(
          String? uid, String? parkingId, bool? isFavorite) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [uid, parkingId, isFavorite],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<String>> getUserFavorites(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #getUserFavorites,
          [uid],
        ),
        returnValue: _i4.Stream<List<String>>.empty(),
      ) as _i4.Stream<List<String>>);
}
