// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgbFCIdDu00fQsB7HZkabrA6pwLiRUo3M',
    appId: '1:208306661715:web:56361706a62f1e546099a6',
    messagingSenderId: '208306661715',
    projectId: 'parkly-69906',
    authDomain: 'parkly-69906.firebaseapp.com',
    storageBucket: 'parkly-69906.firebasestorage.app',
    measurementId: 'G-DHVJ607PLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaZsRGiVa_c0knwKK5k7Paieoy8Akuybc',
    appId: '1:208306661715:android:aff6c6a04233082f6099a6',
    messagingSenderId: '208306661715',
    projectId: 'parkly-69906',
    storageBucket: 'parkly-69906.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYznkqOqQLsFfkzTRt7JHHsFd0xBd1x8w',
    appId: '1:208306661715:ios:b9241b2b02891bae6099a6',
    messagingSenderId: '208306661715',
    projectId: 'parkly-69906',
    storageBucket: 'parkly-69906.firebasestorage.app',
    iosBundleId: 'com.parkly.parkly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgbFCIdDu00fQsB7HZkabrA6pwLiRUo3M',
    appId: '1:208306661715:web:893f44a8e39322576099a6',
    messagingSenderId: '208306661715',
    projectId: 'parkly-69906',
    authDomain: 'parkly-69906.firebaseapp.com',
    storageBucket: 'parkly-69906.firebasestorage.app',
    measurementId: 'G-9WTDR3RTWL',
  );
}
